# Generated by Django 3.2.7 on 2021-12-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_name', models.CharField(max_length=55)),
                ('price', models.IntegerField()),
                ('shoe_colour', models.CharField(max_length=100)),
                ('shoe_description', models.TextField()),
                ('available_now', models.BooleanField()),
            ],
        ),
    ]
